### PR TITLE
About page rendered from notion #11

### PR DESCRIPTION
**Pull request by kartikp36**
New "About Us" page that renders from Notion [#11](https://github.com/gita/GitaGPT/issues/11)

### CODE REVIEW

**Comment by samanyougarg** [comment]
Very cool :)

**Comment by samanyougarg** [comment]
- [ ] Add a "Home" button on the navbar so user can navigate back to the chat page.

**Comment by samanyougarg** [comment]
- [ ] Navbar has issues on mobile.

**Comment by samanyougarg** [comment]
- [ ] Most links are giving a 404.

Screenshot 2023-02-10 at 10 38 58 PM

**Comment by samanyougarg** [comment]
- [ ] Also, fix the conflicts.

**Comment by kartikp36** [comment]
Hey @samanyougarg, I noticed we closed this original PR #27 and merged another one #38. Could you please take a moment and let me know if I made any mistakes for future reference?

**Pull request closed without merging**
